### ISSUE TITLE
방향전환 설정 탭

### ISSUE THREAD

**Issue by waterflower808** [waterflower808/Tetris#1]
tetris model내의
    def getRotatedOffsets(self, direction):
        tmpCoords = Shape.shapeCoord[self.shape]
         ifdirection == 0 or self.shape == Shape.shapeO:
            return ((x, y) for x, y in tmpCoords)
중에서 
          ifdirection == 0 or self.shape == Shape.shapeO:
의미가 무엇인지 제 추측상 방향전환 횟수가 맞는지 궁금합니다

**Comment by n13246** [comment]
특정블록은 돌려도 모양이 변하지 않거나 블록모양이 돌렸을떄 겹치는것을 구별하여 돌리는 키를 입력시 출력될 블록을 계산하는 코드입니다.
