### ISSUE TITLE
도형회전코드 수정하여 오류해결

### ISSUE THREAD

**Issue by n13246** [waterflower808/Tetris#4]
몇몇 도형들이 회전이 안되기에 코드수정 필요

**Comment by waterflower808** [comment]
shapeCoord = (
        ((0, 0), (0, 0), (0, 0), (0, 0)),
        ((0, -1), (0, 0), (0, 1), (0, 2),(0,-2)),
        ((0, 0), (0, 2), (0, 1), (1, 0),(0, -1)),
        ((-1, 0), (0, 0), (1, 0), (2, 0),(0, 1)),
        ((0, -1), (0, 0), (0, 1), (1, 0),(-1, 0)),
        ((0, 0), (0, -1), (1, 0), (1, -1),(2, 0)),
        ((0, 0), (1, 0), (-1, 0), (1, 1),(-1, -1)),
        ((0, 0), (0, -1), (0, 1), (1, 1),(1, -1)),
        ((0, 1), (0, 0), (1, 0), (1, -1),(2, -1)),
    )
이렇게 블록들이 변경되어졌기 때문에

기존의 소스 코드
def getRotatedOffsets(self, direction):
        tmpCoords = Shape.shapeCoord[self.shape]
        if direction == 0 or self.shape == Shape.shapeO:
            return ((x, y) for x, y in tmpCoords)

        if direction == 1:
            return ((-y, x) for x, y in tmpCoords)

        if direction == 2:
            if self.shape in (Shape.shapeI, Shape.shapeZ, Shape.shapeS):
                return ((x, y) for x, y in tmpCoords)
            else:
                return ((-x, -y) for x, y in tmpCoords)

        if direction == 3:
            if self.shape in (Shape.shapeI, Shape.shapeZ, Shape.shapeS,shape.shapeX):
                return ((-y, x) for x, y in tmpCoords)
            else:
                return ((y, -x) for x, y in tmpCoords)
이부분에 각 도형 회전 갯수에 맞춰 몇몇 코드들 바뀌어야 한다고 생각됩니다.
